import Link from "next/link";
import { RefreshCw } from "lucide-react";
import Button from "@/components/ui/Button";
import { services } from "@/lib/constants";

export type Report = {
  businessAssessment: string;
  brandingAssessment: string;
  keyProblems: string[];
  opportunities: string[];
  recommendedActions: string[];
  suggestedServices: string[];
  nextSteps: string;
};

export default function ConsultantReport({
  report,
  onReset,
}: {
  report: Report;
  onReset: () => void;
}) {
  const matchedServices = services.filter((s) =>
    report.suggestedServices?.some(
      (name) => name.toLowerCase() === s.name.toLowerCase()
    )
  );

  return (
    <div className="flex flex-col gap-10">
      <div className="flex items-center justify-between border-b border-ink-line pb-4">
        <p className="eyebrow">Your AI Assessment</p>
        <button
          onClick={onReset}
          className="flex items-center gap-1.5 text-xs text-ash hover:text-gold"
        >
          <RefreshCw size={13} /> Start over
        </button>
      </div>

      <ReportSection title="Business Assessment" text={report.businessAssessment} />
      <ReportSection title="Branding Assessment" text={report.brandingAssessment} />

      <ReportList title="Key Problems" items={report.keyProblems} />
      <ReportList title="Opportunities" items={report.opportunities} />
      <ReportList title="Recommended Actions" items={report.recommendedActions} numbered />

      {matchedServices.length > 0 && (
        <div>
          <p className="eyebrow">Suggested Arch Consult Services</p>
          <div className="mt-4 grid gap-px overflow-hidden bg-ink-line sm:grid-cols-2">
            {matchedServices.map((service) => (
              <Link
                key={service.slug}
                href={`/services/${service.slug}`}
                className="group bg-ink p-5 transition-colors hover:bg-ink-soft"
              >
                <h3 className="font-display text-lg text-paper-white group-hover:text-gold">
                  {service.name}
                </h3>
                <p className="mt-1 text-xs text-ash">{service.summary}</p>
              </Link>
            ))}
          </div>
        </div>
      )}

      <ReportSection title="Next Steps" text={report.nextSteps} />

      <div className="border-t border-ink-line pt-8">
        <p className="text-xs text-ash">
          This assessment is generated by AI based on what you shared, and
          isn't a substitute for a full consultation. No outcome or result is
          guaranteed.
        </p>
        <div className="mt-5 flex flex-col gap-3 sm:flex-row">
          <Button href="/book-consultation" showArrow>
            Book a Human Consultation
          </Button>
          <Button href="/health-check" variant="outline-dark">
            Run the Business Health Check
          </Button>
        </div>
      </div>
    </div>
  );
}

function ReportSection({ title, text }: { title: string; text: string }) {
  return (
    <div>
      <p className="eyebrow">{title}</p>
      <p className="mt-3 text-[15px] leading-relaxed text-ash">{text}</p>
    </div>
  );
}

function ReportList({
  title,
  items,
  numbered = false,
}: {
  title: string;
  items: string[];
  numbered?: boolean;
}) {
  if (!items?.length) return null;
  return (
    <div>
      <p className="eyebrow">{title}</p>
      <ul className="mt-4 flex flex-col gap-3">
        {items.map((item, i) => (
          <li key={item} className="flex gap-3 text-[15px] leading-relaxed text-paper-white">
            {numbered ? (
              <span className="font-display text-sm text-gold">
                {String(i + 1).padStart(2, "0")}
              </span>
            ) : (
              <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-gold" />
            )}
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
