import type { Metadata } from "next";
import PageHero from "@/components/shared/PageHero";
import ConsultantIntake from "@/components/ai-consultant/ConsultantIntake";

export const metadata: Metadata = {
  title: "AI Business Consultant",
  description:
    "Describe your business, industry, challenges and goals, and get a structured AI-generated strategic assessment from Arch Consult.",
};

export default function AIConsultantPage() {
  return (
    <>
      <PageHero
        eyebrow="AI Business Consultant"
        title="Tell me about your business. I'll help you find the next strategic move."
        description="Answer a few specific questions and get a structured assessment covering your business, your branding, key problems, opportunities, and recommended next steps — generated by AI, and never a substitute for a full human consultation."
      />

      <section className="py-16 lg:py-24">
        <div className="container-arch max-w-2xl">
          <ConsultantIntake />
        </div>
      </section>
    </>
  );
}
